# Generated by Django 4.2 on 2023-04-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
